### ISSUE TITLE
Definition lists outside the "terms of definitions"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ribose-iso#2]
Sometimes abbreviations are listed outside the "terms and definitions" section.

There should be a way of marking a list to have the "terms and definitions" style:

For example, in ISO/IEC 27017, it has these sections:

```
3.1 Terms and definitions

For the purposes of this document, the terms and definitions given in ISO/IEC 27000, Recommendation ITU-T Y.3500 | ISO/IEC 17788, Recommendation ITU-T Y.3502 | ISO/IEC 17789, and the following apply.

3.1.1
capability
quality of being able to perform a given activity
[SOURCE: ISO 19440:2007, 3.1.5]
...
```

```
3.2 Abbreviated terms

For the purposes of this document, the following abbreviations apply.

IaaS    Infrastructure as a Service
PaaS    Platform as a Service
PII     Personally Identifiable Information
...
```

**Comment by opoudjis** [comment]
OK, no problem with permitting definition lists elsewhere in the document, I just wanted to confirm they were needed. I have not been through ISO/IEC DIR 2 yet (I only got up as far as the title), but I'll put `dl` into the document model alongside `ul` and `ol`.
